#!/usr/bin/env sh

. "$(dirname -- "$0")/_/husky.sh"

case "$OS" in
    Windows_NT)
        cd packages/web && yarn.cmd run pre-commit && yarn.cmd test
    ;;
    *)
        cd packages/web && yarn run pre-commit && yarn test
    ;;
esac
